### ISSUE TITLE
Web Accessibility Testing 

### ISSUE THREAD

**Issue by cad448** [cad448/mywebclass-simulation#36]
[User Story 15] - Perform testing and resolve issues (if necessary) about web accessibility features

Add to the web accessibility slides (positive and negative tests) in the product development report: https://docs.google.com/presentation/d/16x4Uw5gjX3Bh5jPk8W1s8dpi8prtMamjNfAiI8nLLQU/edit#slide=id.g2225de9676f_0_65

**Comment by bryan52419** [comment]
web accessibility testing is not necessary the website is simple enough to navigate. there where no issues to resolve.
